source 'https://rubygems.org'

# Padrino supports Ruby version 1.9 and later
# ruby '2.3.0'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'
gem 'awesome_print'

# Component requirements
gem 'activesupport', '>= 3.1'
gem 'bcrypt'
gem 'haml'
gem 'mongoid', '>= 3.0.0'

# Test requirements

# Padrino Stable Gem
gem 'padrino', '0.14.1.1'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core support gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.14.1.1'
# end
