development:
 sessions:
   options:
 clients: #Replace clients with sessions to work with Mongoid version 3.x or 4.x
   default:
     database: controle_projetos
     hosts:
       - localhost:27017
 options:
   raise_not_found_error: false